import type { SatFormatSnapshot, SatFormatoManifestItem } from "./types"

const SAT_PAGE = "https://www.sat.gob.mx/minisitio/ActividadesVulnerables/index.html"
const SAT_FORMATOS_BASE = "https://www.sat.gob.mx/minisitio/ActividadesVulnerables/documentos/Formatos"
const VERIFIED_AT = "2026-05-12"
const DEFAULT_ZERO_REPORT_XLSM = "0-InformeEnCeros.xlsm"
const DEFAULT_ZERO_REPORT_SIZE = 1196727

function url(path: string) {
  return `${SAT_FORMATOS_BASE}/${path}`
}

function formato(
  input: Omit<
    SatFormatoManifestItem,
    "satPageUrl" | "sourceLastVerified" | "xmlActivityCode" | "xmlNamespace" | "xmlSchemaLocation" | "xmlLayoutId"
  > & {
    xmlActivityCode?: string
    xmlNamespace?: string
    xmlSchemaLocation?: string
    xmlLayoutId?: string
  },
): SatFormatoManifestItem {
  const xmlActivityCode = input.xmlActivityCode || input.claveActividad
  const xmlNamespace = input.xmlNamespace || `http://www.uif.shcp.gob.mx/recepcion/${xmlActivityCode.toLowerCase()}`
  return {
    ...input,
    xmlActivityCode,
    xmlNamespace,
    xmlSchemaLocation: input.xmlSchemaLocation || `${xmlNamespace} ${xmlActivityCode.toLowerCase()}.xsd`,
    xmlLayoutId: input.xmlLayoutId || input.id,
    satPageUrl: SAT_PAGE,
    sourceLastVerified: VERIFIED_AT,
  }
}

export const SAT_FORMATOS_ACTIVIDADES: SatFormatoManifestItem[] = [
  formato({
    id: "sat-fraccion-i-juegos",
    fraccion: "Fracción I",
    anexo: "Anexo 1",
    actividadKeys: ["fraccion-i-juegos"],
    nombre: "Juegos con apuesta, concursos o sorteos",
    claveActividad: "JAS",
    layoutXmlTag: "juegos_sorteos",
    folletoUrl: url("Fraccion_I/folleto.pdf"),
    informeCerosUrl: url("Fraccion_I/informeenceros.zip"),
    avisoUrl: url("Fraccion_I/juegosysorteos.zip"),
    plantillaAvisoNombre: "JuegosySorteos_v4_3.xlsm",
    plantillaInformeNombre: DEFAULT_ZERO_REPORT_XLSM,
    officialXlsmName: "JuegosySorteos_v4_3.xlsm",
    officialZipLastModified: "Fri, 24 Apr 2026 19:31:40 GMT",
    officialZipSize: 4160632,
    zeroReportZipLastModified: "Fri, 24 Apr 2026 19:31:47 GMT",
    zeroReportZipSize: DEFAULT_ZERO_REPORT_SIZE,
    layoutStatus: "oficial_verificado",
    outputModes: ["informe_ceros", "aviso_normal", "aviso_24h"],
  }),
  formato({
    id: "sat-fraccion-ii-tarjetas-servicios",
    fraccion: "Fracción II",
    anexo: "Anexo 2-A",
    actividadKeys: ["fraccion-ii-tarjetas-servicios"],
    nombre: "Tarjetas de servicios o crédito",
    claveActividad: "TSC",
    layoutXmlTag: "tarjetas_servicios_credito",
    folletoUrl: url("Fraccion_II_monederos/folleto.pdf"),
    informeCerosUrl: url("Fraccion_II_tarjetascredito/informeenceros.zip"),
    avisoUrl: url("Fraccion_II_tarjetascredito/tarjetasservcred.zip"),
    plantillaAvisoNombre: "TarjetasServCred_v4_3.xlsm",
    plantillaInformeNombre: DEFAULT_ZERO_REPORT_XLSM,
    officialXlsmName: "TarjetasServCred_v4_3.xlsm",
    officialZipLastModified: "Fri, 24 Apr 2026 19:31:40 GMT",
    officialZipSize: 4128925,
    zeroReportZipLastModified: "Fri, 24 Apr 2026 19:31:47 GMT",
    zeroReportZipSize: DEFAULT_ZERO_REPORT_SIZE,
    layoutStatus: "oficial_verificado",
    outputModes: ["informe_ceros", "aviso_normal", "aviso_24h"],
  }),
  formato({
    id: "sat-fraccion-ii-tarjetas-prepagadas",
    fraccion: "Fracción II",
    anexo: "Anexo 2-B",
    actividadKeys: ["fraccion-ii-tarjetas-prepagadas"],
    nombre: "Tarjetas prepagadas",
    claveActividad: "TPP",
    layoutXmlTag: "tarjetas_prepagadas",
    folletoUrl: url("Fraccion_II_monederos/folleto.pdf"),
    informeCerosUrl: url("Fraccion_II_tarjetasprepagadas/informeenceros.zip"),
    avisoUrl: url("Fraccion_II_tarjetasprepagadas/tarjetasprepago.zip"),
    plantillaAvisoNombre: "TarjetasPrepago_v4_3.xlsm",
    plantillaInformeNombre: DEFAULT_ZERO_REPORT_XLSM,
    officialXlsmName: "TarjetasPrepago_v4_3.xlsm",
    officialZipLastModified: "Fri, 24 Apr 2026 19:31:47 GMT",
    officialZipSize: 4135723,
    zeroReportZipLastModified: "Fri, 24 Apr 2026 19:31:40 GMT",
    zeroReportZipSize: DEFAULT_ZERO_REPORT_SIZE,
    layoutStatus: "oficial_verificado",
    outputModes: ["informe_ceros", "aviso_normal", "aviso_24h"],
  }),
  formato({
    id: "sat-fraccion-ii-instrumentos-valor",
    fraccion: "Fracción II",
    anexo: "Anexo 2-C",
    actividadKeys: ["fraccion-ii-instrumentos-valor"],
    nombre: "Instrumentos de almacenamiento de valor monetario",
    claveActividad: "TAV",
    layoutXmlTag: "tarjetas_valor_monetario",
    folletoUrl: url("Fraccion_II_monederos/folleto.pdf"),
    informeCerosUrl: url("Fraccion_II_monederos/informeenceros.zip"),
    avisoUrl: url("Fraccion_II_monederos/tarjetasdevrwd.zip"),
    plantillaAvisoNombre: "TarjetasDevRwd_v4_3.xlsm",
    plantillaInformeNombre: DEFAULT_ZERO_REPORT_XLSM,
    officialXlsmName: "TarjetasDevRwd_v4_3.xlsm",
    officialZipLastModified: "Fri, 24 Apr 2026 19:31:40 GMT",
    officialZipSize: 4131013,
    zeroReportZipLastModified: "Fri, 24 Apr 2026 19:31:40 GMT",
    zeroReportZipSize: DEFAULT_ZERO_REPORT_SIZE,
    layoutStatus: "oficial_verificado",
    outputModes: ["informe_ceros", "aviso_normal", "aviso_24h"],
  }),
  formato({
    id: "sat-fraccion-iii-cheques",
    fraccion: "Fracción III",
    anexo: "Anexo 3",
    actividadKeys: ["fraccion-iii-cheques"],
    nombre: "Cheques de viajero",
    claveActividad: "CHV",
    layoutXmlTag: "cheques_viajero",
    folletoUrl: url("Fraccion_III/folleto.pdf"),
    informeCerosUrl: url("Fraccion_III/informeenceros.zip"),
    avisoUrl: url("Fraccion_III/chequesviajero.zip"),
    plantillaAvisoNombre: "ChequesViajero_v4_4.xlsm",
    plantillaInformeNombre: DEFAULT_ZERO_REPORT_XLSM,
    officialXlsmName: "ChequesViajero_v4_4.xlsm",
    officialZipLastModified: "Fri, 24 Apr 2026 19:31:40 GMT",
    officialZipSize: 4139813,
    zeroReportZipLastModified: "Fri, 24 Apr 2026 19:31:34 GMT",
    zeroReportZipSize: DEFAULT_ZERO_REPORT_SIZE,
    layoutStatus: "oficial_verificado",
    outputModes: ["informe_ceros", "aviso_normal", "aviso_24h"],
  }),
  formato({
    id: "sat-fraccion-iv-prestamos",
    fraccion: "Fracción IV",
    anexo: "Anexo 4",
    actividadKeys: ["fraccion-iv-prestamos"],
    nombre: "Mutuo, préstamo, crédito o garantía",
    claveActividad: "MCG",
    layoutXmlTag: "mutuo_prestamo_credito",
    folletoUrl: url("Fraccion_IV/folleto.pdf"),
    informeCerosUrl: url("Fraccion_IV/informeenceros.zip"),
    avisoUrl: url("Fraccion_IV/mutuoprestcred.zip"),
    plantillaAvisoNombre: "MutuoPrestCred_v4_3.xlsm",
    plantillaInformeNombre: DEFAULT_ZERO_REPORT_XLSM,
    officialXlsmName: "MutuoPrestCred_v4_3.xlsm",
    officialZipLastModified: "Fri, 24 Apr 2026 19:31:31 GMT",
    officialZipSize: 4228018,
    zeroReportZipLastModified: "Fri, 24 Apr 2026 19:31:40 GMT",
    zeroReportZipSize: DEFAULT_ZERO_REPORT_SIZE,
    layoutStatus: "oficial_verificado",
    outputModes: ["informe_ceros", "aviso_normal", "aviso_24h"],
  }),
  formato({
    id: "sat-fraccion-v-inmuebles",
    fraccion: "Fracción V",
    anexo: "Anexo 5",
    actividadKeys: ["fraccion-v-inmuebles"],
    nombre: "Construcción, desarrollo, comercialización o transmisión de inmuebles",
    claveActividad: "INM",
    layoutXmlTag: "inmuebles",
    folletoUrl: url("Fraccion_V_desarrolloinmobiliario/folleto.pdf"),
    informeCerosUrl: url("Fraccion_V_transmisionderechos/informeenceros.zip"),
    avisoUrl: url("Fraccion_V_transmisionderechos/inmuebles.zip"),
    plantillaAvisoNombre: "Inmuebles_v4_5.xlsm",
    plantillaInformeNombre: DEFAULT_ZERO_REPORT_XLSM,
    officialXlsmName: "Inmuebles_v4_5.xlsm",
    officialZipLastModified: "Fri, 24 Apr 2026 19:31:40 GMT",
    officialZipSize: 4230906,
    zeroReportZipLastModified: "Fri, 24 Apr 2026 19:31:34 GMT",
    zeroReportZipSize: DEFAULT_ZERO_REPORT_SIZE,
    layoutStatus: "oficial_verificado",
    outputModes: ["informe_ceros", "aviso_normal", "informe_27_bis", "aviso_24h"],
  }),
  formato({
    id: "sat-fraccion-v-bis-desarrollo",
    fraccion: "Fracción V Bis",
    anexo: "Anexo 5-A",
    actividadKeys: ["fraccion-v-bis-desarrollo"],
    nombre: "Recepción de recursos para desarrollo inmobiliario",
    claveActividad: "VBI",
    layoutXmlTag: "desarrollos_inmobiliarios",
    folletoUrl: url("Fraccion_Vbis/folleto.pdf"),
    informeCerosUrl: url("Fraccion_Vbis/informeenceros.zip"),
    avisoUrl: url("Fraccion_Vbis/avisos.zip"),
    plantillaAvisoNombre: "DesarrollosInmobiliarios_v4_7.xlsm",
    plantillaInformeNombre: DEFAULT_ZERO_REPORT_XLSM,
    officialXlsmName: "DesarrollosInmobiliarios_v4_7.xlsm",
    officialZipLastModified: "Fri, 24 Apr 2026 19:31:34 GMT",
    officialZipSize: 4830209,
    zeroReportZipLastModified: "Fri, 24 Apr 2026 19:31:40 GMT",
    zeroReportZipSize: DEFAULT_ZERO_REPORT_SIZE,
    layoutStatus: "oficial_verificado",
    outputModes: ["informe_ceros", "aviso_normal", "informe_27_bis", "aviso_24h"],
  }),
  formato({
    id: "sat-fraccion-vi-metales",
    fraccion: "Fracción VI",
    anexo: "Anexo 6",
    actividadKeys: ["fraccion-vi-metales"],
    nombre: "Metales, piedras preciosas, joyas o relojes",
    claveActividad: "MJO",
    layoutXmlTag: "metales_joyas",
    folletoUrl: url("Fraccion_VI/folleto.pdf"),
    informeCerosUrl: url("Fraccion_VI/informeenceros.zip"),
    avisoUrl: url("Fraccion_VI/metalesyjoyas.zip"),
    plantillaAvisoNombre: "MetalesyJoyas_v4_3.xlsm",
    plantillaInformeNombre: DEFAULT_ZERO_REPORT_XLSM,
    officialXlsmName: "MetalesyJoyas_v4_3.xlsm",
    officialZipLastModified: "Fri, 24 Apr 2026 19:31:34 GMT",
    officialZipSize: 4137057,
    zeroReportZipLastModified: "Fri, 24 Apr 2026 19:31:34 GMT",
    zeroReportZipSize: DEFAULT_ZERO_REPORT_SIZE,
    layoutStatus: "oficial_verificado",
    outputModes: ["informe_ceros", "aviso_normal", "aviso_24h"],
  }),
  formato({
    id: "sat-fraccion-vii-arte",
    fraccion: "Fracción VII",
    anexo: "Anexo 7",
    actividadKeys: ["fraccion-vii-arte"],
    nombre: "Subasta o venta de obras de arte",
    claveActividad: "OBA",
    layoutXmlTag: "obras_arte",
    folletoUrl: url("Fraccion_VII/folleto.pdf"),
    informeCerosUrl: url("Fraccion_VII/informeenceros.zip"),
    avisoUrl: url("Fraccion_VII/obrasarte.zip"),
    plantillaAvisoNombre: "ObrasArte_v4_3.xlsm",
    plantillaInformeNombre: DEFAULT_ZERO_REPORT_XLSM,
    officialXlsmName: "ObrasArte_v4_3.xlsm",
    officialZipLastModified: "Fri, 24 Apr 2026 19:31:47 GMT",
    officialZipSize: 4135654,
    zeroReportZipLastModified: "Fri, 24 Apr 2026 19:31:34 GMT",
    zeroReportZipSize: DEFAULT_ZERO_REPORT_SIZE,
    layoutStatus: "oficial_verificado",
    outputModes: ["informe_ceros", "aviso_normal", "aviso_24h"],
  }),
  formato({
    id: "sat-fraccion-viii-vehiculos",
    fraccion: "Fracción VIII",
    anexo: "Anexo 8",
    actividadKeys: ["fraccion-viii-vehiculos"],
    nombre: "Vehículos aéreos, marítimos o terrestres",
    claveActividad: "VEH",
    layoutXmlTag: "vehiculos",
    folletoUrl: url("Fraccion_VIII/folleto.pdf"),
    informeCerosUrl: url("Fraccion_VIII/informeenceros.zip"),
    avisoUrl: url("Fraccion_VIII/vehiculos.zip"),
    plantillaAvisoNombre: "Vehiculos_v4_4.xlsm",
    plantillaInformeNombre: DEFAULT_ZERO_REPORT_XLSM,
    officialXlsmName: "Vehiculos_v4_4.xlsm",
    officialZipLastModified: "Fri, 24 Apr 2026 19:31:40 GMT",
    officialZipSize: 4155222,
    zeroReportZipLastModified: "Fri, 24 Apr 2026 19:31:34 GMT",
    zeroReportZipSize: DEFAULT_ZERO_REPORT_SIZE,
    layoutStatus: "oficial_verificado",
    outputModes: ["informe_ceros", "aviso_normal", "aviso_24h"],
  }),
  formato({
    id: "sat-fraccion-ix-blindaje",
    fraccion: "Fracción IX",
    anexo: "Anexo 9",
    actividadKeys: ["fraccion-ix-blindaje"],
    nombre: "Servicios de blindaje",
    claveActividad: "BLI",
    layoutXmlTag: "blindaje",
    folletoUrl: url("Fraccion_IX/folleto.pdf"),
    informeCerosUrl: url("Fraccion_IX/informeenceros.zip"),
    avisoUrl: url("Fraccion_IX/blindaje.zip"),
    plantillaAvisoNombre: "Blindaje_v4_4.xlsm",
    plantillaInformeNombre: DEFAULT_ZERO_REPORT_XLSM,
    officialXlsmName: "Blindaje_v4_4.xlsm",
    officialZipLastModified: "Fri, 24 Apr 2026 19:31:34 GMT",
    officialZipSize: 4139935,
    zeroReportZipLastModified: "Fri, 24 Apr 2026 19:31:31 GMT",
    zeroReportZipSize: DEFAULT_ZERO_REPORT_SIZE,
    layoutStatus: "oficial_verificado",
    outputModes: ["informe_ceros", "aviso_normal", "aviso_24h"],
  }),
  formato({
    id: "sat-fraccion-x-traslado",
    fraccion: "Fracción X",
    anexo: "Anexo 10",
    actividadKeys: ["fraccion-x-traslado"],
    nombre: "Traslado o custodia de dinero o valores",
    claveActividad: "TCV",
    layoutXmlTag: "traslado_custodia_valores",
    folletoUrl: url("Fraccion_X/folleto.pdf"),
    informeCerosUrl: url("Fraccion_X/informeenceros.zip"),
    avisoUrl: url("Fraccion_X/traslcustvalores.zip"),
    plantillaAvisoNombre: "TraslCustValores_v4_3.xlsm",
    plantillaInformeNombre: DEFAULT_ZERO_REPORT_XLSM,
    officialXlsmName: "TraslCustValores_v4_3.xlsm",
    officialZipLastModified: "Fri, 24 Apr 2026 19:31:34 GMT",
    officialZipSize: 4189423,
    zeroReportZipLastModified: "Fri, 24 Apr 2026 19:31:31 GMT",
    zeroReportZipSize: DEFAULT_ZERO_REPORT_SIZE,
    layoutStatus: "oficial_verificado",
    outputModes: ["informe_ceros", "aviso_normal", "aviso_24h"],
  }),
  formato({
    id: "sat-fraccion-xi-servicios-profesionales",
    fraccion: "Fracción XI",
    anexo: "Anexo 11",
    actividadKeys: [
      "fraccion-xi-a-inmuebles",
      "fraccion-xi-b-administracion",
      "fraccion-xi-c-cuentas",
      "fraccion-xi-d-aportaciones",
      "fraccion-xi-e-corporativo",
    ],
    nombre: "Servicios profesionales independientes",
    claveActividad: "SPR",
    layoutXmlTag: "servicios_profesionales",
    folletoUrl: url("Fraccion_XI/folleto.pdf"),
    informeCerosUrl: url("Fraccion_XI/informeenceros.zip"),
    avisoUrl: url("Fraccion_XI/avisos.zip"),
    plantillaAvisoNombre: "Paquete múltiple de plantillas oficiales (.zip)",
    plantillaInformeNombre: DEFAULT_ZERO_REPORT_XLSM,
    officialXlsmName: "Paquete múltiple de plantillas oficiales (.zip)",
    officialZipLastModified: "Fri, 24 Apr 2026 19:31:47 GMT",
    officialZipSize: 43240094,
    zeroReportZipLastModified: "Fri, 24 Apr 2026 19:31:31 GMT",
    zeroReportZipSize: DEFAULT_ZERO_REPORT_SIZE,
    layoutStatus: "paquete_multiple",
    outputModes: ["informe_ceros", "aviso_normal", "informe_27_bis", "aviso_24h"],
  }),
  formato({
    id: "sat-fraccion-xii-fe-publica",
    fraccion: "Fracción XII",
    anexo: "Anexo 12",
    actividadKeys: [
      "fraccion-xii-notarios-a",
      "fraccion-xii-notarios-b",
      "fraccion-xii-notarios-c",
      "fraccion-xii-notarios-d",
      "fraccion-xii-notarios-e",
      "fraccion-xii-corredores-a",
      "fraccion-xii-corredores-b",
      "fraccion-xii-corredores-c",
      "fraccion-xii-corredores-d",
    ],
    nombre: "Servicios de fe pública",
    claveActividad: "FEP",
    layoutXmlTag: "fe_publica",
    folletoUrl: url("Fraccion_XII/folleto.pdf"),
    informeCerosUrl: url("Fraccion_XII/informeenceros.zip"),
    avisoUrl: url("Fraccion_XII/avisos.zip"),
    plantillaAvisoNombre: "Paquete múltiple de plantillas oficiales (.zip)",
    plantillaInformeNombre: DEFAULT_ZERO_REPORT_XLSM,
    officialXlsmName: "Paquete múltiple de plantillas oficiales (.zip)",
    officialZipLastModified: "Fri, 24 Apr 2026 19:31:40 GMT",
    officialZipSize: 17324804,
    zeroReportZipLastModified: "Fri, 24 Apr 2026 19:31:40 GMT",
    zeroReportZipSize: 1709853,
    layoutStatus: "paquete_multiple",
    outputModes: ["informe_ceros", "aviso_normal", "informe_27_bis", "aviso_24h"],
  }),
  formato({
    id: "sat-fraccion-xiii-donativos",
    fraccion: "Fracción XIII",
    anexo: "Anexo 13",
    actividadKeys: ["fraccion-xiii-donativos"],
    nombre: "Recepción de donativos",
    claveActividad: "DON",
    layoutXmlTag: "donativos",
    folletoUrl: url("Fraccion_XIII/folleto.pdf"),
    informeCerosUrl: url("Fraccion_XIII/informeenceros.zip"),
    avisoUrl: url("Fraccion_XIII/donativos.zip"),
    plantillaAvisoNombre: "Donativos_v4_3.xlsm",
    plantillaInformeNombre: DEFAULT_ZERO_REPORT_XLSM,
    officialXlsmName: "Donativos_v4_3.xlsm",
    officialZipLastModified: "Fri, 24 Apr 2026 19:31:34 GMT",
    officialZipSize: 4136761,
    zeroReportZipLastModified: "Fri, 24 Apr 2026 19:31:34 GMT",
    zeroReportZipSize: DEFAULT_ZERO_REPORT_SIZE,
    layoutStatus: "oficial_verificado",
    outputModes: ["informe_ceros", "aviso_normal", "aviso_24h"],
  }),
  formato({
    id: "sat-fraccion-xiv-comercio-exterior",
    fraccion: "Fracción XIV",
    anexo: "Anexo 14",
    actividadKeys: [
      "fraccion-xiv-aduanal-a",
      "fraccion-xiv-aduanal-b",
      "fraccion-xiv-aduanal-c",
      "fraccion-xiv-aduanal-d",
      "fraccion-xiv-aduanal-e",
      "fraccion-xiv-aduanal-f",
    ],
    nombre: "Servicios de comercio exterior",
    claveActividad: "ADU",
    layoutXmlTag: "comercio_exterior",
    folletoUrl: url("Fraccion_XIV/folleto.pdf"),
    informeCerosUrl: url("Fraccion_XIV/aviso.zip"),
    avisoUrl: url("Fraccion_XIV/aviso.zip"),
    plantillaAvisoNombre: DEFAULT_ZERO_REPORT_XLSM,
    plantillaInformeNombre: DEFAULT_ZERO_REPORT_XLSM,
    officialXlsmName: DEFAULT_ZERO_REPORT_XLSM,
    officialZipLastModified: "Fri, 24 Apr 2026 19:31:47 GMT",
    officialZipSize: DEFAULT_ZERO_REPORT_SIZE,
    zeroReportZipLastModified: "Fri, 24 Apr 2026 19:31:47 GMT",
    zeroReportZipSize: DEFAULT_ZERO_REPORT_SIZE,
    layoutStatus: "informe_por_pedimento",
    outputModes: ["informe_ceros", "aviso_normal", "aviso_24h"],
  }),
  formato({
    id: "sat-fraccion-xv-arrendamiento",
    fraccion: "Fracción XV",
    anexo: "Anexo 15",
    actividadKeys: ["fraccion-xv-uso-goce"],
    nombre: "Derechos personales de uso o goce de bienes inmuebles",
    claveActividad: "ARI",
    xmlActivityCode: "ARI",
    xmlNamespace: "http://www.uif.shcp.gob.mx/recepcion/ari",
    xmlSchemaLocation: "http://www.uif.shcp.gob.mx/recepcion/ari ari.xsd",
    xmlLayoutId: "sat-xml-arrendamiento-v4-5",
    layoutXmlTag: "arrendamiento",
    folletoUrl: url("Fraccion_XV/folleto.pdf"),
    informeCerosUrl: url("Fraccion_XV/informeenceros.zip"),
    avisoUrl: url("Fraccion_XV/arrendamiento.zip"),
    plantillaAvisoNombre: "Arrendamiento_v4_5.xlsm",
    plantillaInformeNombre: DEFAULT_ZERO_REPORT_XLSM,
    officialXlsmName: "Arrendamiento_v4_5.xlsm",
    officialZipLastModified: "Fri, 24 Apr 2026 19:31:47 GMT",
    officialZipSize: 4190962,
    zeroReportZipLastModified: "Fri, 24 Apr 2026 19:31:47 GMT",
    zeroReportZipSize: DEFAULT_ZERO_REPORT_SIZE,
    layoutStatus: "oficial_verificado",
    outputModes: ["informe_ceros", "aviso_normal", "informe_27_bis", "aviso_24h"],
  }),
  formato({
    id: "sat-fraccion-xvi-activos-virtuales",
    fraccion: "Fracción XVI",
    anexo: "Anexo 16",
    actividadKeys: [
      "fraccion-xvi-activos-virtuales",
      "fraccion-xvi-activos-virtuales-operacion",
      "fraccion-xvi-activos-virtuales-contraprestacion",
    ],
    nombre: "Proveedores de activos virtuales",
    claveActividad: "AVT",
    layoutXmlTag: "activos_virtuales",
    folletoUrl: url("Fraccion_XVI/folleto.pdf"),
    informeCerosUrl: url("Fraccion_XVI/informeenceros.zip"),
    avisoUrl: url("Fraccion_XVI/aviso.zip"),
    plantillaAvisoNombre: "ActivosVirtuales_v1.2.xlsm",
    plantillaInformeNombre: DEFAULT_ZERO_REPORT_XLSM,
    officialXlsmName: "ActivosVirtuales_v1.2.xlsm",
    officialZipLastModified: "Fri, 24 Apr 2026 19:31:40 GMT",
    officialZipSize: 4874676,
    zeroReportZipLastModified: "Fri, 24 Apr 2026 19:31:34 GMT",
    zeroReportZipSize: DEFAULT_ZERO_REPORT_SIZE,
    layoutStatus: "oficial_verificado",
    outputModes: ["informe_ceros", "aviso_normal", "aviso_24h"],
  }),
]

export function resolveSatFormatoForActividad(actividadKey: string): SatFormatoManifestItem {
  const formato = SAT_FORMATOS_ACTIVIDADES.find((item) => item.actividadKeys.includes(actividadKey))

  if (!formato) {
    throw new Error(`Formato SAT no configurado para actividad vulnerable: ${actividadKey}`)
  }

  return formato
}

export function buildSatFormatSnapshot(generatedAt = VERIFIED_AT): SatFormatSnapshot {
  return {
    schemaVersion: 1,
    source: SAT_PAGE,
    generatedAt,
    items: SAT_FORMATOS_ACTIVIDADES,
  }
}
