export const demoFraccionXV = {
  actividadKey: "fraccion-xv-uso-goce",
  periodo: {
    anio: 2025,
    mes: 2,
    fechaOperacion: "2025-02-10",
    fechaInicioContrato: "2025-02-01",
    fechaFinContrato: "2026-01-31",
    fechaPago: "2025-02-05",
  },
  cliente: {
    tipo: "pm_mexicana",
    detalle: "Servicios de arrendamiento inmobiliario",
    nombre: "Grupo Arrendador Demo, S.A. de C.V.",
    rfc: "GAD990101AA1",
    mismoGrupo: false,
    tipoOperacion: "Arrendamiento corporativo anual",
    monto: "180000",
    moneda: "MXN",
  },
  inmueble: {
    codigoOperacion: "501",
    figuraCliente: "1",
    figuraSujetoObligado: "1",
    referenciaAviso: "DEMO-FXV-001",
    alertaCodigo: "0",
    alertaDescripcion: "",
    prioridadAviso: "1",
    claveSujetoObligado: "DEM0001234",
    claveActividad: "15",
    tipoInmueble: "oficina",
    valorAvaluo: "4500000",
    folioReal: "FOLIO-VALLE-2025",
    pais: "MX",
    entidad: "Nuevo León",
    municipio: "San Pedro Garza García",
    ciudad: "San Pedro Garza García",
    colonia: "Del Valle Oriente",
    codigoPostal: "66260",
    calle: "Av. Gómez Morín",
    numeroExterior: "123",
    numeroInterior: "12B",
  },
  liquidacion: {
    formaPago: "1",
    instrumento: "1",
  },
  beneficiario: {
    tipo: "persona_fisica",
    nombre: "Laura",
    apellidoPaterno: "Martínez",
    apellidoMaterno: "Flores",
    fechaNacimiento: "1988-07-22",
    rfc: "MAFL880722AB2",
    curp: "MAFL880722MNLTRR05",
    pais: "MX",
  },
  contraparte: {
    tipo: "persona_fisica",
    nombre: "Carlos",
    apellidoPaterno: "Ramírez",
    apellidoMaterno: "Soto",
    fechaNacimiento: "1982-11-03",
    rfc: "RASO821103H32",
    pais: "MX",
  },
  instrumento: {
    numero: "11234",
    fecha: "2024-12-15",
    notario: "Lic. Gabriela Luna, Notaría 25",
    entidad: "Nuevo León",
    valorAvaluo: "4500000",
  },
  personaAviso: {
    tipo: "persona_moral",
    denominacion: "Grupo Arrendador Demo, S.A. de C.V.",
    fechaConstitucion: "2005-08-12",
    pais: "MX",
    giro: "Servicios de arrendamiento inmobiliario",
    rfc: "GAD990101AA1",
    domicilio: {
      ambito: "nacional",
      pais: "MX",
      entidad: "Nuevo León",
      municipio: "San Pedro Garza García",
      ciudad: "San Pedro Garza García",
      colonia: "Del Valle Oriente",
      codigoPostal: "66260",
      calle: "Av. Gómez Morín",
      numeroExterior: "123",
      numeroInterior: "12B",
    },
    contacto: {
      clavePais: "MX",
      telefono: "8180010020",
      correo: "contacto@grupodemo.mx",
    },
  },
  expediente: {
    rfc: "GAD990101AA1",
    nombre: "Grupo Arrendador Demo, S.A. de C.V.",
    tipoCliente: "pm_mexicana",
    detalleTipoCliente: "Servicios de arrendamiento inmobiliario",
    responsable: "María Gómez",
    claveSujetoObligado: "DEM0001234",
    claveActividadVulnerable: "15",
    identificacion: {
      giro: "Arrendamiento de espacios corporativos",
      "actividad-economica": "Servicios inmobiliarios y de alquiler de bienes muebles",
      "origen-recursos": "Ingresos por contratos de arrendamiento a clientes corporativos",
    },
    datosFiscales: {
      "regimen-fiscal": "General de Ley Personas Morales",
      "actividad-sat": "531120 - Arrendamiento de bienes inmuebles",
      "registro-publico": "Folio mercantil 45987",
    },
    perfilOperaciones: {
      "origen-fondos": "Cobro de rentas anticipadas y depósitos de garantía",
      "destino-fondos": "Mantenimiento de inmuebles y pago a proveedores",
    },
    documentacion: {
      "identificacion-oficial": "completo",
      "acta-constitutiva": "completo",
      "situacion-fiscal": "completo",
      "comprobante-domicilio": "en-proceso",
    },
    personas: [
      {
        id: "demo-cliente",
        tipo: "persona_moral",
        denominacion: "Grupo Arrendador Demo, S.A. de C.V.",
        fechaConstitucion: "2005-08-12",
        rfc: "GAD990101AA1",
        pais: "MX",
        giro: "Arrendamiento y administración de inmuebles corporativos",
        rolRelacion: "Cliente arrendador",
        representante: {
          nombre: "Carlos",
          apellidoPaterno: "Ramírez",
          apellidoMaterno: "Soto",
          fechaNacimiento: "1982-11-03",
          rfc: "RASO821103H32",
          curp: "RASO821103HNLRTR03",
        },
        domicilio: {
          ambito: "nacional",
          pais: "MX",
          entidad: "Nuevo León",
          municipio: "San Pedro Garza García",
          ciudad: "San Pedro Garza García",
          colonia: "Del Valle Oriente",
          codigoPostal: "66260",
          calle: "Av. Gómez Morín",
          numeroExterior: "123",
          numeroInterior: "12B",
        },
        contacto: {
          conoceTelefono: "si",
          conocePaisTelefono: "si",
          clavePais: "MX",
          telefono: "8180010020",
          correo: "contacto@grupodemo.mx",
        },
        identificacion: {
          tipo: "Acta constitutiva",
          numero: "Libro 24, Tomo II",
          pais: "MX",
          fechaVencimiento: "",
        },
        participacion: {
          porcentajeCapital: "100",
          origenRecursos: "Rentas corporativas",
          esPep: "no",
          detallePep: "",
        },
      },
      {
        id: "demo-beneficiario",
        tipo: "persona_fisica",
        denominacion: "Laura Martínez Flores",
        fechaConstitucion: "",
        rfc: "MAFL880722AB2",
        curp: "MAFL880722MNLTRR05",
        pais: "MX",
        giro: "Beneficiario final",
        rolRelacion: "Beneficiario final",
        representante: {
          nombre: "",
          apellidoPaterno: "",
          apellidoMaterno: "",
          fechaNacimiento: "",
          rfc: "",
          curp: "",
        },
        domicilio: {
          ambito: "nacional",
          pais: "MX",
          entidad: "Nuevo León",
          municipio: "San Pedro Garza García",
          ciudad: "San Pedro Garza García",
          colonia: "Del Valle Oriente",
          codigoPostal: "66260",
          calle: "Av. Lázaro Cárdenas",
          numeroExterior: "250",
          numeroInterior: "",
        },
        contacto: {
          conoceTelefono: "si",
          conocePaisTelefono: "si",
          clavePais: "MX",
          telefono: "8112345678",
          correo: "laura.martinez@example.com",
        },
        identificacion: {
          tipo: "INE",
          numero: "0000000000000",
          pais: "MX",
          fechaVencimiento: "2032-05-15",
        },
        participacion: {
          porcentajeCapital: "35",
          origenRecursos: "Honorarios profesionales",
          esPep: "no",
          detallePep: "",
        },
      },
    ],
  },
} as const
