import { dispatchStorageEvent, isBrowser, readJsonStorage, writeJsonStorage } from "./storage"

export const ALERT_STORAGE_KEY = "pld-alerts"

export type AlertSeverity = "info" | "warning" | "danger"

export type AlertCategory = "document-expiry" | "custom"

export interface AlertRecord {
  id: string
  module: string
  resourceId?: string
  title: string
  description: string
  severity: AlertSeverity
  dueDate?: string | null
  createdAt: string
  status: "open" | "resolved"
  category: AlertCategory
  autoGenerated: boolean
}

function generateId(): string {
  if (typeof crypto !== "undefined" && "randomUUID" in crypto) {
    return crypto.randomUUID()
  }
  return `${Date.now()}-${Math.random().toString(36).slice(2, 10)}`
}

function readAlerts(): AlertRecord[] {
  const alerts = readJsonStorage<AlertRecord[]>(ALERT_STORAGE_KEY, [])
  return alerts
}

function writeAlerts(alerts: AlertRecord[]): void {
  writeJsonStorage(ALERT_STORAGE_KEY, alerts)
  dispatchStorageEvent(ALERT_STORAGE_KEY)
}

export function getAlerts(options: { module?: string; includeResolved?: boolean } = {}): AlertRecord[] {
  const alerts = readAlerts()
  return alerts
    .filter((alert) => {
      if (options.module && alert.module !== options.module) return false
      if (!options.includeResolved && alert.status === "resolved") return false
      return true
    })
    .sort((a, b) => {
      const aDate = a.dueDate ? new Date(a.dueDate).getTime() : new Date(a.createdAt).getTime()
      const bDate = b.dueDate ? new Date(b.dueDate).getTime() : new Date(b.createdAt).getTime()
      return aDate - bDate
    })
}

export function resolveAlert(id: string): void {
  if (!isBrowser()) return
  const alerts = readAlerts().map((alert) => (alert.id === id ? { ...alert, status: "resolved" } : alert))
  writeAlerts(alerts)
}

export function registerAlert(alert: Omit<AlertRecord, "id" | "createdAt" | "status" | "autoGenerated"> & {
  autoGenerated?: boolean
  status?: AlertRecord["status"]
}): AlertRecord {
  if (!isBrowser()) throw new Error("Alert registration is only available in the browser")
  const record: AlertRecord = {
    ...alert,
    id: generateId(),
    createdAt: new Date().toISOString(),
    status: alert.status ?? "open",
    autoGenerated: alert.autoGenerated ?? false,
  }
  const alerts = readAlerts()
  writeAlerts([...alerts, record])
  return record
}

interface SyncDocumentAlertInput {
  module: string
  documents: {
    id: string
    name: string
    dueDate: Date | null | undefined
  }[]
  warningThresholdDays?: number
  criticalThresholdDays?: number
}

export function syncDocumentAlerts({
  module,
  documents,
  warningThresholdDays = 30,
  criticalThresholdDays = 7,
}: SyncDocumentAlertInput): AlertRecord[] {
  if (!isBrowser()) return []

  const now = new Date()
  const alerts = readAlerts()
  const filtered = alerts.filter(
    (alert) => !(alert.module === module && alert.category === "document-expiry" && alert.autoGenerated),
  )

  const updatedAlerts = [...filtered]

  documents.forEach((doc) => {
    if (!doc.dueDate) {
      return
    }

    const dueDate = doc.dueDate
    const diffDays = Math.ceil((dueDate.getTime() - now.getTime()) / (1000 * 60 * 60 * 24))

    let severity: AlertSeverity | null = null
    let description = ""

    if (diffDays < 0) {
      severity = "danger"
      description = `El documento ${doc.name} está vencido desde ${dueDate.toLocaleDateString()}.`
    } else if (diffDays <= criticalThresholdDays) {
      severity = "danger"
      description = `El documento ${doc.name} vence en ${diffDays} día${diffDays === 1 ? "" : "s"}.`
    } else if (diffDays <= warningThresholdDays) {
      severity = "warning"
      description = `El documento ${doc.name} vence en ${diffDays} día${diffDays === 1 ? "" : "s"}.`
    }

    if (severity) {
      const existing = alerts.find(
        (alert) =>
          alert.module === module &&
          alert.category === "document-expiry" &&
          alert.resourceId === doc.id &&
          alert.autoGenerated,
      )

      if (existing) {
        updatedAlerts.push({
          ...existing,
          severity,
          description,
          dueDate: dueDate.toISOString(),
          status: "open",
        })
      } else {
        updatedAlerts.push({
          id: generateId(),
          module,
          resourceId: doc.id,
          title: `Renovación de ${doc.name}`,
          description,
          severity,
          dueDate: dueDate.toISOString(),
          createdAt: new Date().toISOString(),
          status: "open",
          category: "document-expiry",
          autoGenerated: true,
        })
      }
    }
  })

  writeAlerts(updatedAlerts)
  return getAlerts({ module, includeResolved: true })
}
